# Generated by Django 5.2.15 on 2026-06-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClaimFileBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("total_rows", models.IntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_id", models.CharField(blank=True, max_length=100, null=True)),
                ("patient_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("doctor_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "doctor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("visit_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "insurance_copay",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "patient_copay",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "medicine_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("facility", models.CharField(blank=True, max_length=255, null=True)),
                ("diagnosis", models.TextField(blank=True, null=True)),
                (
                    "row_integrity_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="core.claimfilebatch",
                    ),
                ),
            ],
        ),
    ]
